### ISSUE TITLE
modify yaml structure for compatibility with other apps

### ISSUE THREAD

**Issue by audiracmichelle** [NSAPH-Data-Processing/global_geoboundaries#3]
```
global_ADM1:
    url: null
    year: xxx
    idvar: shapeID
    output_idvar: id
global_ADM2:
    url: null
    year: xxx
    idvar: shapeID
    output_idvar: id
global_ADM3:
    url: xxx
    year: xxx
    idvar: shapeID
    output_idvar: id
```
